// Builds the TTF fork of the plugin from the upstream plugin file:
//   plugin/upstream_minecraft_title_generator.js (Ewan Howell's plugin, unchanged)
//   + ttf/plugin_additions.js + ttf/ttf_converter.cjs
//   -> plugin/minecraft_title_generator_ttf.js
// Every change is a checked string replacement, so a new upstream version either applies cleanly
// or fails loudly here.
import fs from "node:fs"
import path from "node:path"

const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"))
const repo = path.resolve(here, "..")
let src = fs.readFileSync(path.join(repo, "plugin", "upstream_minecraft_title_generator.js"), "utf8").replace(/\r\n/g, "\n")

function replace(from, to, count = 1) {
  const n = src.split(from).length - 1
  if (n !== count) throw new Error(`Expected ${count} match(es) for ${JSON.stringify(from.slice(0, 80))}, found ${n}`)
  src = src.split(from).join(to)
}

// 1. Own ids for everything Blockbench registers, so the fork and upstream can be installed side
// by side: format, mode, actions, dialogs, preview, presets storage, camera preset, DOM ids.
src = src.replace(/minecraft_title(?!_generator)/g, "minecraft_title_ttf")
src = src.replace(/minecraft_title_generator/g, "minecraft_title_generator_ttf")
src = src.replace(/minecraft-title-render-controls/g, "minecraft-title-ttf-render-controls")
replace(`id: "minecraft-title",`, `id: "minecraft-title-ttf",`)
replace(`formats: ["minectaft_title"]`, `formats: ["minecraft_title_ttf"]`)
replace(`const name = "Minecraft Title Generator"`, `const name = "Minecraft Title Generator (TTF fork)"`)
replace(`const description = "Create Minecraft-styled title models!"`, `const description = "Create Minecraft-styled title models! Fork of Ewan Howell's plugin that can import TTF/OTF fonts."`)
replace(`version: "1.10.4",`, `version: "1.10.4-ttf.1",`)
replace(`        name: "Minecraft Title",
`, `        name: "Minecraft Title (TTF fork)",
`)

// 2. Header.
if (!src.startsWith("(async () => {\n")) throw new Error("Unexpected plugin start")
src = src.replace(`(async () => {\n`, `(async () => {
  // Minecraft Title Generator by Ewan Howell (https://ewanhowell.com/plugins/minecraft-title-generator/).
  // TTF fork: generated by ttf/build_plugin.mjs from the upstream plugin; every change is marked
  // "TTF fork". Do not edit this file, edit ttf/plugin_additions.js or ttf/build_plugin.mjs.
`)

// 3. The fork's code and the converter, inside the plugin's closure.
const converter = fs.readFileSync(path.join(here, "ttf_converter.cjs"), "utf8")
  .replace(/\r\n/g, "\n")
  .replace(`if (typeof module !== "undefined") module.exports = TTFConverter\n`, "")
const additions = fs.readFileSync(path.join(here, "plugin_additions.js"), "utf8").replace(/\r\n/g, "\n")
replace(`  const api = "https://api.wynem.com"\n`, `  const api = "https://api.wynem.com"\n\n  // TTF fork: converter, copied from ttf/ttf_converter.cjs\n${converter.split("\n").map(l => l ? "  " + l : l).join("\n")}\n${additions}\n`)

// 4. Hooks.
replace(`    async onload() {\n`, `    async onload() {\n      ttfOnLoad() // TTF fork\n`)
replace(`    onunload() {\n`, `    onunload() {\n      ttfOnUnload() // TTF fork\n`)
replace(`        async onBuild() {\n          getFontTextures("minecraft-ten-blank", true)`, `        async onBuild() {\n          await ttfRestored // TTF fork: imported fonts\n          getFontTextures("minecraft-ten-blank", true)`)
replace(`      const r = await fetch(\`\${root}/\${path}\`)\n`, `      if (ttfIsLocal(root)) return await ttfFetchLocal(root, path) // TTF fork: local folder\n      const r = await fetch(\`\${root}/\${path}\`)\n`)
replace(`          const r = await fetch(\`\${connection.roots[x]}/\${path}\`)\n`, `          if (ttfIsLocal(connection.roots[x])) { // TTF fork: local folder
            const data = await ttfFetchLocal(connection.roots[x], path)
            root = connection.roots[x]
            connection.rootIndex = x
            return data
          }
          const r = await fetch(\`\${connection.roots[x]}/\${path}\`)\n`)
replace(`  function sendStats(args, font) {\n`, `  function sendStats(args, font) {\n    if (fonts[args.font]?.textureSource) return // TTF fork: no usage stats for fonts upstream does not have\n`)

// 5. textureSource: textures and overlays come from another font's folder.
replace("    const data = await fetchData(`${fonts[font].type}s/${font}/textures.json`, () => ({ textures: {}, overlays: {} }))\n",
  "    const ttfSource = fonts[font].textureSource ?? font // TTF fork: shared textures\n    const data = await fetchData(`${fonts[font].type}s/${ttfSource}/textures.json`, () => ({ textures: {}, overlays: {} }))\n")
replace("      texture.texture = `${fonts[font].type}s/${font}/textures/${id}.png`\n", "      texture.texture = `${fonts[font].type}s/${ttfSource}/textures/${id}.png`\n")
replace("        variant.texture = `${fonts[font].type}s/${font}/textures/${id}.png`\n", "        variant.texture = `${fonts[font].type}s/${ttfSource}/textures/${id}.png`\n")
replace("      overlay.texture = `${fonts[font].type}s/${font}/overlays/${id}.png`\n", "      overlay.texture = `${fonts[font].type}s/${ttfSource}/overlays/${id}.png`\n")

// 6. Texture thumbnails: imported fonts have none of their own and show the source font's.
replace(`'s/' + font + '/thumbnails/'`, `'s/' + (fonts[font].thumbnailFont ?? font) + '/thumbnails/'`, 7)

const out = path.join(repo, "plugin", "minecraft_title_generator_ttf.js")
fs.writeFileSync(out, src)
console.log(`${out}: ${src.length} bytes`)
